### ISSUE TITLE
Upgrade to 1.1.2 fails

### ISSUE THREAD

**Issue by matthiasn** [MarcelGarus/glados#12]
@MarcelGarus I'm having an issue with upgrading again. I'm relatively certain I had filed something similar before but I can't seem to find the issue any more. Not as urgent this time, at least I don't have to remove the library for the time being, I only cannot upgrade.

Thanks for looking into this, and for your work on this useful library.

```

Because test >=1.20.0 depends on test_api 0.4.9 and test >=1.19.4 <1.20.0 depends on test_api 0.4.8, test >=1.19.4 requires test_api 0.4.8 or 0.4.9.
And because glados >=1.1.2 depends on test ^1.19.5 and every version of flutter_test from sdk depends on test_api 0.4.3, glados >=1.1.2 is incompatible with flutter_test from sdk.
So, because lotti depends on both flutter_test from sdk and glados ^1.1.2, version solving failed.
Running "flutter pub get" in lotti...
pub get failed (1; So, because lotti depends on both flutter_test from sdk and glados ^1.1.2,
version solving failed.)
```

**Comment by MarcelGarus** [comment]
Hi again! On which Flutter version are you? (You can check with `flutter --version`.)
I assume the issue is that you are using some version of Flutter lower than 2.9. Recently, PR https://github.com/MarcelGarus/glados/pull/11 updated some dependencies and thereby broke compatibility with Flutter versions below 2.9.

That's totally okay though. If you don't want to update yet, don't feel obligated to rush into it. The new package version only updates the dependencies and doesn't offer any new features or bug fixes anyways.

**Comment by MarcelGarus** [comment]
I'm going to close this because of inactivity.
