### ISSUE TITLE
setUp and tearDown per test iteration

### ISSUE THREAD

**Issue by jibbers42** [MarcelGarus/glados#14]
Is there a way to run setUp and tearDown per test iteration?

**Comment by MarcelGarus** [comment]
Sadly not because Glados internally calls `test` only once. If I'd call `test` for every generated input, then the `test` function would catch the error directly and print the result without propagating the failing to Glados. That would make the shrinking of inputs impossible.

I recommend simply calling those methods manually in the function:

```dart
void setUp() { ... }
void tearDown() { ... }

Glados<int>().test('something', (a) {
  setUp();
  ...
  tearDown();
});
```
